/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefetrj.mg.bsi.agenda.view;

import br.cefetrj.mg.bsi.agenda.config.Settings;
import br.cefetrj.mg.bsi.agenda.controller.ContatoController;
import br.cefetrj.mg.bsi.utils.Utils;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author cristian
 */
public class FormContato extends javax.swing.JFrame {

    /**
     * Creates new form FormContato
     */
    ContatoController controller;

    public FormContato() {
        initComponents();
        controller = new ContatoController();
        controller.setForm(this);

    }

    public JTextField getjTxtEnd() {
        return jTxtEnd;
    }

    public void setjTxtEnd(JTextField jTxtEnd) {
        this.jTxtEnd = jTxtEnd;
    }

    public JButton getjBtnCadAtualizar() {
        return jBtnCadAtualizar;
    }

    public void setjBtnCadAtualizar(JButton jBtnCadAtualizar) {
        this.jBtnCadAtualizar = jBtnCadAtualizar;
    }

    public JButton getjBtnExcluir() {
        return jBtnExcluir;
    }

    public void setjBtnExcluir(JButton jBtnExcluir) {
        this.jBtnExcluir = jBtnExcluir;
    }

    public JFormattedTextField getjTxtDataNasc() {
        return jTxtDataNasc;
    }

    public void setjTxtDataNasc(JFormattedTextField jTxtDataNasc) {
        this.jTxtDataNasc = jTxtDataNasc;
    }

    public JTextField getjTxtEmail() {
        return jTxtEmail;
    }

    public void setjTxtEmail(JTextField jTxtEmail) {
        this.jTxtEmail = jTxtEmail;
    }

    public JTextField getjTxtNome() {
        return jTxtNome;
    }

    public void setjTxtNome(JTextField jTxtNome) {
        this.jTxtNome = jTxtNome;
    }

    public JFormattedTextField getjTxtTel() {
        return jTxtTel;
    }

    public void setjTxtTel(JFormattedTextField jTxtTel) {
        this.jTxtTel = jTxtTel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtTel = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtDataNasc = new javax.swing.JFormattedTextField();
        jBtnCadAtualizar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTxtEnd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, -1));

        jLabel2.setText("E-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        try {
            jTxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, -1));

        jLabel4.setText("Data de Nasc.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        try {
            jTxtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTxtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, -1));

        jBtnCadAtualizar.setText("Cadastrar");
        jBtnCadAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCadAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 380, -1));

        jBtnExcluir.setText("Excluir");
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, -1));

        jLabel5.setText("Endereço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        getContentPane().add(jTxtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadAtualizarActionPerformed
        // TODO add your handling code here:
        if (jBtnCadAtualizar.getText().equalsIgnoreCase("cadastrar")) {
            if (controller.inserir()) {
                Utils.print(Settings.msg, Settings.TITLE, Settings.status);
                limpar();
            } else {
                Utils.print(Settings.msg, Settings.TITLE, Settings.status);
            }
        } else {
            if (controller.atualizar()) {
                Utils.print(Settings.msg, Settings.TITLE, Settings.status);
                limpar();
            } else {
                Utils.print(Settings.msg, Settings.TITLE, Settings.status);
            }
        }

    }//GEN-LAST:event_jBtnCadAtualizarActionPerformed

    private void limpar() {
        JTextField txt[] = {
            jTxtDataNasc,
            jTxtEmail,
            jTxtEnd,
            jTxtNome,
            jTxtTel
        };
        for (JTextField t : txt) {
            t.setText("");
        }
        jTxtNome.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadAtualizar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField jTxtDataNasc;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEnd;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JFormattedTextField jTxtTel;
    // End of variables declaration//GEN-END:variables
}
